fragment client on Client{
  id
  name
  url
  self
  date
  update
} 

query findClients($id:ID!){
    clients(query:{id:[$id]}){
        ...client
    }
}

mutation createClient($name:String!,$url:String!){
    createClient(name:$name,url:$url){
        ...client
    }
}