fragment profile on Profile{
    id
    self
    name
    text
    date
    update
    sn
}

query findProfiles($query:ProfileQuery!){
    profiles(query:$query){
        ...profile
    }
}

mutation createProfile($name:String!,$text:String!,$sn:String!){
    createProfile(name:$name,text:$text,sn:$sn){
        ...profile
    }
}