#import "./topic.gql"
#import "./profile.gql"
#import "./history.gql"

fragment resBase on Res{
    id
    topic{
        ...topic
    }
    date
    self
    uv
    dv
    hash
    replyCount
    voteFlag
}

fragment res on Res{
    ...resBase
    ...resNormalBase
    ...resHistoryBase
    ...resForkBase
    ...resDeleteBase
}

fragment resNormalBase on ResNormal{
    name
    text
    reply{id}
    profile{
        ...profile
    }
    isReply
}

fragment resNormal on ResNormal{
    ...resBase
    ...resNormalBase
}

fragment resHistoryBase on ResHistory{
    history{
        ...history
    }
}

fragment resHistory on ResHistory{
    ...resBase
    ...resHistoryBase
}

fragment resTopic on ResTopic{
    ...resBase
}

fragment resForkBase on ResFork{
    fork{
        ...topicFork
    }
}

fragment resFork on ResFork{
    ...resBase
    ...resForkBase
}

fragment resDeleteBase on ResDelete{
    flag
}

fragment resDelete on ResDelete{
    ...resBase
    ...resDeleteBase
}

query findReses($query:ResQuery!){
    reses(query:$query){
        ...res
    }
}

mutation voteRes($res:ID!,$type:VoteType!){
    voteRes(res:$res,type:$type){
        ...res
    }
}

mutation delRes($res:ID!){
    delRes(res:$res){
        ...res
    }
}

mutation createRes($topic:String!,$name:String,$text:String!,$reply:String,$profile:String,$age:Boolean!){
    createRes(topic:$topic,name:$name,text:$text,reply:$reply,profile:$profile,age:$age){
        ...resNormal
    }
}

subscription resAdded($topic:ID!){
  resAdded(topic:$topic){
    count
    res{
        ...res
    }
  }
}