#import "./client.gql"
#import "./token-req.gql"

fragment tokenBase on Token{
    id
    key
    date
}

fragment token on Token{
    ...tokenBase
    ...tokenGeneralBase
}

fragment tokenMaster on TokenMaster{
    ...tokenBase
}

fragment tokenGeneralBase on TokenGeneral{
    client{
        ...client
    }
}

fragment tokenGeneral on TokenGeneral{
    ...tokenBase
    ...tokenGeneralBase
}

mutation createTokenMaster($auth:AuthUser!){
    createTokenMaster(auth:$auth){
        ...token
    }
}

mutation createTokenGeneral($client:ID!){
    createTokenGeneral(client:$client){
        token{
            ...tokenGeneral
        }
        req{
            ...tokenReq
        }
    }
}