#import "./client.gql"

fragment tokenBase on Token{
    id
    key
    date
}

fragment token on Token{
    ...tokenBase
    ...tokenGeneralBase
}

fragment tokenMaster on TokenMaster{
    ...tokenBase
}

fragment tokenGeneralBase on TokenGeneral{
    client{
        ...client
    }
}

fragment tokenGeneral on TokenGeneral{
    ...tokenBase
    ...tokenGeneralBase
}