fragment topicBase on Topic{
    id
    title
    update
    date
    resCount
    active
} 

fragment topicSearchBase on TopicSearch{
    tags
    text
}

fragment topicSearch on TopicSearch{
    ...topicBase
    ...topicSearchBase
}

fragment topicNormal on TopicNormal{
    ...topicSearch
}

fragment topicOne on TopicOne{
    ...topicSearch
}

fragment topicForkBase on TopicFork{
    parent{
        ...topicSearch
    }
}

fragment topicFork on TopicFork{
    ...topicBase
    ...topicForkBase
}

fragment topic on Topic{
    ...topicBase
    ...topicSearchBase
    ...topicForkBase
} 

mutation createTopicNormal($title:String!,$tags:[String!]!,$text:String!){
    createTopicNormal(title:$title,tags:$tags,text:$text){
        ...topic
    }
}

mutation createTopicOne($title:String!,$tags:[String!]!,$text:String!){
    createTopicOne(title:$title,tags:$tags,text:$text){
        ...topic
    }
}

query findTopics($query:TopicQuery!){
    topics(query:$query){
        ...topic
    }
}

query findTopicTags{
    topicTags{
        name
        count
    }
}