fragment user on User{
    id
    sn
} 

query findUserSN($id:ID!){
    userSN(id:$id)
}

mutation updateUser($sn:String!,$pass:String!,$auth:AuthUser!){
    updateUser(sn:$sn,pass:$pass,auth:$auth){
        ...user
    }
}

query findUserID($sn:String!){
    userID(sn:$sn)
}

mutation createUser($sn:String!,$pass:String!,$recaptcha:String!){
    createUser(sn:$sn,pass:$pass,recaptcha:$recaptcha){
        ...user
    }
}