#import "../../gql/user.gql"
#import "../../gql/token.gql"

query findSN($id:ID!){
    userSN(id:$id)
}

mutation updateUser($sn:String!,$pass:String!,$auth:AuthUser!){
    updateUser(sn:$sn,pass:$pass,auth:$auth){
        ...user
    }
}

mutation createTokenMaster2($auth:AuthUser!){
    createTokenMaster(auth:$auth){
        ...token
    }
}