#import "../gql/topic.gql"

query findTopicFork($parent:ID!){
    topics(query:{parent:$parent}){
        ...topicFork
    }
}

mutation createTopicFork($title:String!,$parent:ID!){
    createTopicFork(title:$title,parent:$parent){
        ...topicFork
    }
}